In [207]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import numpy as np

samples = ['awesome unicorns are awesome','batman forever and ever','I love batman forever','I love batman forever']
bigram_vectorizer = TfidfVectorizer(ngram_range=(2, 2),binary=True) 
co_occurrences = bigram_vectorizer.fit_transform(samples)
print('Printing sparse matrix:', co_occurrences) 
print('Printing dense matrix :', co_occurrences.todense()) 
sum_occ = np.sum(co_occurrences.todense(),axis=0)
#print('Sum of word-word occurrences:', sum_occ)
print('Pretty printig of co_occurrences count:', zip(bigram_vectorizer.get_feature_names(),np.array(sum_occ)[0].tolist()))

Printing sparse matrix:   (0, 2)	0.57735026919
  (0, 6)	0.57735026919
  (0, 1)	0.57735026919
  (1, 3)	0.411377911334
  (1, 4)	0.644502992261
  (1, 0)	0.644502992261
  (2, 3)	0.62922751467
  (2, 5)	0.777221162079
  (3, 3)	0.62922751467
  (3, 5)	0.777221162079
Printing dense matrix : [[ 0.          0.57735027  0.57735027  0.          0.          0.
   0.57735027]
 [ 0.64450299  0.          0.          0.41137791  0.64450299  0.          0.        ]
 [ 0.          0.          0.          0.62922751  0.          0.77722116
   0.        ]
 [ 0.          0.          0.          0.62922751  0.          0.77722116
   0.        ]]
Pretty printig of co_occurrences count: <zip object at 0x107ca2208>


In [86]:
bigram_vectorizer.get_feature_names()


['and ever',
 'are awesome',
 'awesome unicorns',
 'batman forever',
 'forever and',
 'love batman',
 'unicorns are']

In [96]:
b = bigram_vectorizer.idf_

b[3]

1.2876820724517808

In [97]:
b

array([ 1.69314718,  1.69314718,  1.69314718,  1.28768207,  1.69314718,
        1.69314718,  1.69314718])

In [24]:
from numpy import *
import numpy

def entropy(counts):
    '''Compute entropy.'''
    ps = counts/float(sum(counts))  # coerce to float and normalize
    ps = ps[nonzero(ps)]            # toss out zeros
    H = -sum(ps * numpy.log2(ps))   # compute entropy
    
    return H

def

SyntaxError: invalid syntax (<ipython-input-24-f011fbc5178e>, line 2)

In [75]:
import nltk, math

In [115]:
import re, string, numpy, itertools

In [132]:
v = np.array([])
v = numpy.append(v,[2,3])
v = numpy.append(v,[4,5])
v/2

array([ 1. ,  1.5,  2. ,  2.5])

In [133]:
b = [-i[0,0]*numpy.log2(i[0,0]) for i in a[:,0] if i[0,0] != 0]
sum(b)

sum([0.3,0,1])

1.3

In [208]:
import numpy as np
import itertools 

def entropy(vec):
    b = [-i*numpy.log2(i) for i in vec if i != 0]
    return sum(b)
            
def theta(i,x,a,k):
    #print("theta:",(a[i,x] + k) % 2,k,x)
    return (a[i,x] + k) % 2

bigram_vectorizer = CountVectorizer(ngram_range=(2, 2),binary=True) 
co_occurrences = bigram_vectorizer.fit_transform(samples)   
bigram_tfidf_vectorizer = TfidfVectorizer(ngram_range=(2, 2),binary=True) 
co_occurrences_tfidf = bigram_tfidf_vectorizer.fit_transform(samples) 
idf = bigram_tfidf_vectorizer.idf_

def joint_prob(i,j,a, idf):
    out = np.array([])
    total = np.sum(idf)
    for k,l in itertools.product(range(2),range(2)):
        vec = [theta(i,x,a,k)*theta(j,x,a,l)*idf[x] for x in range(0,len(idf))]
        out = numpy.append(out,sum(vec))
    return out/total

def single_prob(i,a, idf):
    out = np.array([])
    total = np.sum(idf)
    print(total)
    for k in range(2):
        vec = [theta(i,x,a,k)*idf[x] for x in range(0,len(idf))]
        #print(vec)
        out = numpy.append(out,sum(vec))
    return out/total

def partition_function(idf,a):
    pass

def mutual_information(i,j,a,idf):
    single_i = single_prob(i,a, idf)
    single_j = single_prob(j,a, idf)
    joint = joint_prob(i,j,a,idf)
    print(single_i)
    print(single_j)
    print(joint)
    return entropy(single_i) + entropy(single_j) - entropy(joint)
               
    
    
        

In [211]:
mutual_information(3,2,co_occurrences.todense(),idf)
#single_i = single_prob(0,co_occurrences.todense(), idf)

12.3154228345
12.3154228345
[ 0.22199556  0.77800444]
[ 0.22199556  0.77800444]
[ 0.22199556  0.          0.          0.77800444]


0.76379463094498323

In [204]:
print(co_occurrences_tfidf)

  (0, 2)	0.57735026919
  (0, 6)	0.57735026919
  (0, 1)	0.57735026919
  (1, 3)	0.473629601033
  (1, 4)	0.622766007833
  (1, 0)	0.622766007833
  (2, 3)	0.605348508106
  (2, 5)	0.795960541568


In [182]:
2%2

0

In [142]:
co_occurrences_tfidf.todense()

matrix([[0, 1, 1, 0, 0, 0, 1],
        [1, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [ ]:
import numpy as np
import itertools 

def entropy(vec):
    b = [-i*numpy.log2(i) for i in vec if i != 0]
    return sum(b)
            
def theta(i,x,a,k):
    #print("theta:",(a[i,x] + k) % 2,k,x)
    return (a[i,x] + k) % 2

bigram_vectorizer = CountVectorizer(ngram_range=(2, 2)) 
co_occurrences = bigram_vectorizer.fit_transform(samples)   
bigram_tfidf_vectorizer = TfidfVectorizer(ngram_range=(2, 2),binary=True) 
co_occurrences_tfidf = bigram_tfidf_vectorizer.fit_transform(samples) 
idf = bigram_tfidf_vectorizer.idf_

def joint_prob(i,j,a, idf):
    out = np.array([])
    total = np.sum(idf)
    for k,l in itertools.product(range(2),range(2)):
        vec = [theta(i,x,a,k)*theta(j,x,a,l)*idf[x] for x in range(0,len(idf))]
        out = numpy.append(out,sum(vec))
    return out/total

def single_prob(i,a, idf):
    out = np.array([])
    total = np.sum(idf)
    print(total)
    for k in range(2):
        vec = [theta(i,x,a,k)*idf[x] for x in range(0,len(idf))]
        #print(vec)
        out = numpy.append(out,sum(vec))
    return out/total

def partition_function(idf,a):
    pass

def mutual_information(i,j,a,idf):
    single_i = single_prob(i,a, idf)
    single_j = single_prob(j,a, idf)
    joint = joint_prob(i,j,a,idf)
    print(single_i)
    print(single_j)
    print(joint)
    return entropy(single_i) + entropy(single_j) - entropy(joint)
               
    
    
        